### ISSUE TITLE
Updating ItemsSource after sorting won't update grid

### ISSUE THREAD

**Issue by jerone** [akgulebubekir/Xamarin.Forms.DataGrid#10]
When I update (add or remove items) my binding collection, which is attached to `ItemsSource`, changes are reflected in the datagrid.

However, after a header is clicked for sorting, changes to my collection won't update the datagrid anymore.

_DataGrid 1.5.0_
_XF 2.3.2.127_

**Comment by akgulebubekir** [comment]
[OffTopic] I fixed that issue weeks ago and was keeping on stash. Since there are some conflicts on your commited code I couldn't get. Thanks @jerone
