### ISSUE TITLE
Using an ObservableCollection<IDictionary<string, object>> as ItemsSource

### ISSUE THREAD

**Issue by Grochni** [akgulebubekir/Xamarin.Forms.DataGrid#103]
I'm trying to use an `ObservableCollection<IDictionary<string, object>> ` as ItemsSource. I generate the columns dynamically in code behind like this:
`foreach(var key in dict.Keys)`
`{`
`   dataGrid.Columns.Add(new DataGridColumn`
`   {`
`      CellTemplate = ...,`
`      PropertyName = String.Format(CultureInfo.InvariantCulture, "[{0}]", key)`
`   }`
`}`

I know, it seems weird, but I did a similar thing with a ListView before and it worked perfectly too. And also for the DataGrid, the values from my dictionaries are displayed, the only problem is that when I update them in the view (my cells are mostly text entries) the collection doesn't change, even though I used TwoWay bindings everywhere.

Any suggestions?

**Comment by njale** [comment]
Seems like there is a bug in the Android version. When you update an observable collection, the table is not updated even when I do a NotificationUpdate. It works fine on UWP. Have not tried iOS yet.
So far I have not found a work-around.
