### ISSUE TITLE
How can i pass dynamic color to whole row for datagrid in  Xamarin.Forms.DataGrid

### ISSUE THREAD

**Issue by priyankanaga** [akgulebubekir/Xamarin.Forms.DataGrid#106]
<dg:DataGrid x:Name="beanhoperdatagrid" ItemsSource="{Binding list}"  >       

<dg:DataGrid.Columns>
<dg:DataGridColumn Title="status" PropertyName="status"/>
<dg:DataGridColumn Title="version" PropertyName="version"/>                       
 <dg:DataGridColumn Title="Response (s)" PropertyName="Response">

</dg:DataGrid.Columns>

<dg:DataGrid.Triggers>                          
<DataTrigger 
TargetType="dg:DataGrid" Binding="{Binding Path=status}"
 Value="Title">

<Setter Property="BackgroundColor" 
Value="{Binding Converter=
{StaticResource StreakToColorConverter}}"
/>

</DataTrigger>   
                         
</dg:DataGrid.Triggers>
</dg:DataGrid>

I am not able to set color to whole row based on status.
can you please help me how can i set it.

**Comment by DalosProgramos** [comment]
Hello,
Did you find a solution?

**Comment by akgulebubekir** [comment]
`PaletteCollection` implements `IColorProvider` that you can set background color whatever you want. Simply set `RowsBackgroundColorPalette` to your ColorProvider class (example below). 

```
<local:RowBgProvider x:Key="CustomBgProvider"/>
<dg:DataGrid RowsBackgroundColorPalette="{StaticResource CustomBgProvider}">
  ...
</dg:DataGrid>
```

```
public class RowBgProvider: IColorProvider
{
	public Color GetColor(int rowIndex, object item)
	{
		switch(((YourType) item)Status)
		{
			case Status.Error:
				return Color.Red;
			case Status.Warning:
				return Color.Yellow;
			case Status.OK:
				return Color.Green;

			default:
				return Color.LightGray;
		}
	}
}
```

**Comment by DalosProgramos** [comment]
Thanks a lot. :)

**Comment by scriptBoris** [comment]
My row status has been updated - how to update RowsBackgroundColorPalette?
