### ISSUE TITLE
Pull Down Refresh Wheel Color

### ISSUE THREAD

**Issue by sktyjd** [akgulebubekir/Xamarin.Forms.DataGrid#108]
What is the best way to get ahold of the refresh indicator in the DataGrid? Example on iOS you can get ahold of the ViewController with a Custom Renderer and Set the TintColor Property with some of the controls. Is that possible with Xamarin.Forms.DataGrid? Every time I go to check the ViewController Property it is null.

The objective is something like [this](https://alexdunn.org/2017/03/24/xamarin-tips-xamarin-forms-ios-listview-refresh-spinner-color/).

**Comment by akgulebubekir** [comment]
`DataGrid` uses `ListView` behind, so you should write a `ListViewRenderer` as explained the link you shared.
