### ISSUE TITLE
PaletteCollection Color

### ISSUE THREAD

**Issue by dcraggs** [akgulebubekir/Xamarin.Forms.DataGrid#115]
Could

<dg:PaletteCollection>
                    <Color >#F2F2F2</Color>
                    <Color>#FFFFFF</Color>
                </dg:PaletteCollection>

Be changed to

<dg:PaletteCollection>
                    <Color Value ="#F2F2F2"/>
                    <Color Value="#FFFFFF"/r>
                </dg:PaletteCollection>

Then you could use StaticResource items in there like:

<dg:PaletteCollection>
                    <Color Value ="{StaticResource DataGridRow1Color}"/>
                    <Color Value="{StaticResource DataGridRow2Color}"/r>
                </dg:PaletteCollection>

Which can be defiunes in App.xaml

**Comment by akgulebubekir** [comment]
Please check [this ](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/blob/master/Samples.md#usage-with-resource-dictionary) example.
