### ISSUE TITLE
Getting error item template count has exceeded the limit 23 in list view. Even when I am using caching strategy and datatemplate. This datagrid contain around 50 items

### ISSUE THREAD

**Issue by arbellaio** [akgulebubekir/Xamarin.Forms.DataGrid#119]
Even when I am using caching strategy. This datagrid contain around 50 items. Items are added via barcode scanner

**Comment by gmasit** [comment]
Same issue here. For me, it is getting occurred while i am loading multiple times in datagrid.

**Comment by akgulebubekir** [comment]
Please follow.Xamarin's own [issue](https://github.com/xamarin/Xamarin.Forms/issues/2931)
