### ISSUE TITLE
Xamarin WPF

### ISSUE THREAD

**Issue by dhpanteon** [akgulebubekir/Xamarin.Forms.DataGrid#120]
Is that supports Xamarin WPF?

**Comment by tkouba** [comment]
It works

**Comment by Wopin** [comment]
Can anyone tell me what can i do to use it in Xamarin Forms WPF?

All the lines are in black. I dont know if i dont using it right or i dont make init well....

![image](https://user-images.githubusercontent.com/5811345/67075834-3fd2b600-f18c-11e9-8449-d1cdea379953.png)

**Comment by tkouba** [comment]
Nothing special. A have added WPF sample https://github.com/tkouba/Xamarin.Forms.DataGrid/tree/wpf_sample (with updated version of all referenced packages). And you should use hack in file DataGrid.xaml.cs method InitHeaderView:
```
if (Device.RuntimePlatform == Device.WPF)
  _headerView.Padding = new Thickness(BorderThickness.Left + 13, BorderThickness.Top, BorderThickness.Right + 23, 0);
else
  _headerView.Padding = new Thickness(BorderThickness.Left, BorderThickness.Top, BorderThickness.Right, 0);

```
