### ISSUE TITLE
On text change in entry not updating it's binding property 

### ISSUE THREAD

**Issue by 13atec030** [akgulebubekir/Xamarin.Forms.DataGrid#121]
<dg:DataGrid.Columns>
                <dg:DataGridColumn Title="Designation" PropertyName="Designation" Width="0.95*" VerticalContentAlignment="Center">
                    <dg:DataGridColumn.CellTemplate>
                        <DataTemplate>
                            <controls:CustomEntry Text="{Binding}"/>                       
                        </DataTemplate>
                    </dg:DataGridColumn.CellTemplate>
                </dg:DataGridColumn>
                <dg:DataGridColumn Title="Salary" PropertyName="Salary"  Width="1*"/>
            </dg:DataGrid.Columns>

In the above code i am binding "Designation" property to the Text. But while changing text in the  entry "Designation" is not getting updated in ViewModel. It is showing it's initial value.

**Comment by srishalu** [comment]
Have you solved @13atec030  ?

**Comment by 13atec030** [comment]
Yes I solved it. I did some changes in my code. You can take following code reference. 

```
 <dg:DataGrid.Columns>
<dg:DataGridColumn  Title="Designation"  x:Name="dgcDesignation" x:FieldModifier="public"  VerticalContentAlignment="Center"  Width="0.95*">
                        <dg:DataGridColumn.CellTemplate>
                            <DataTemplate>
                                <controls:CustomEntry x:Name="entry" x:FieldModifier="public" Text="{Binding 
                                  Designation}"  CornerRadius="0" BorderWidth="0" 
                                 VerticalOptions="CenterAndExpand"  FontSize="Small" 
                                 HorizontalTextAlignment="Center"/ >
                            </DataTemplate>
                        </dg:DataGridColumn.CellTemplate>
      </dg:DataGridColumn>
 </dg:DataGrid.Columns>

```
