### ISSUE TITLE
Picker is not working inside the DatagridColumn

### ISSUE THREAD

**Issue by srigayathri23** [akgulebubekir/Xamarin.Forms.DataGrid#125]
I have added picker in one of the datagrid column. Binding is not working in picker. I have binded itemssource and ItemDisplayBinding

XAML:

    <dg:DataGridColumn x:Name="GenderColumn" Title="Gender" x:FieldModifier="public" 
       PropertyName="Gender">
      <dg:DataGridColumn.CellTemplate>
       <DataTemplate>
        <Picker x:Name="genderPicker" x:FieldModifier="public" ItemsSource="{Binding > 
          PickerModel,Mode=TwoWay}" ItemDisplayBinding="{Binding 
            GenderTypes,Mode=TwoWay}"/>

                     

C#:

       viewModel.Employees.Add(new Model.DatagridModel()
            {
               PickerModel = new List<PickerModel>() { new PickerModel() { GenderTypes = "Male" }, 
         new PickerModel() { GenderTypes = "Female" } }
            });

Model & ViewModel:

      public class PickerModel
      {
          public string GenderTypes { get; set; }
      }

     public class DatagridModel : INotifyPropertyChanged
      {
        public List<PickerModel> PickerModel { set; get; }          
      }

i have binded Entry in DataColumn and its working. Anyhelp for making Picker to work?

Thanks in advance

**Comment by akgulebubekir** [comment]
this is a known xamarin bug tat hasn't been solved for years([link](https://xamarin.github.io/bugzilla-archives/42/42231/bug.html)). This is also a duplicate issue. Plase check the [original one.](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/issues/1)
