### ISSUE TITLE
Data grid tapped event

### ISSUE THREAD

**Issue by davidbuckleyni** [akgulebubekir/Xamarin.Forms.DataGrid#126]
Hi Does your grid support item tapped that would select the entire row in one go at all its a limitation i am finding in the Telerik grids and was wondering if your grid might support it.

**Comment by njale** [comment]
It does not. I achieved it by using custom renderer and custom property. If you still are interested, let me know and I can post some code to explain it.

**Comment by RaulLuna** [comment]
Hi, njale, I´m interested in this code. Thanks in advance

**Comment by njale** [comment]
Create a control that inherits from the control you want to use in your grid. Must do same thing for every controltype you want to put in your grid. Here is an example for Label:
 
public class GridLabel : Label
    {
        public GridLabel()
        {
            HorizontalOptions = LayoutOptions.CenterAndExpand;
            VerticalOptions = LayoutOptions.CenterAndExpand;
        }

        public static readonly BindableProperty ItemProperty = BindableProperty.Create(nameof(Item), typeof(object), typeof(OilyGridLabel), null, BindingMode.OneWay, null, OnItemPropertyChanged);


        private static void OnItemPropertyChanged(BindableObject bindableObject, object oldValue, object newValue)
        {
            var gridLabel = (GridLabel)bindableObject;
            gridLabel.Item = newValue;
        }

        public object Item
        {
            get => GetValue(ItemProperty);
            set => SetValue(ItemProperty, value);
        }
    }

In your Xaml DataTemplate then use as here:
   <DataTemplate>
            <GridLabel Text="{Binding Something}" **Item="{Binding .}**"/>
    </DataTemplate>

The **Item** custom-property will now contain the containing object, so you can get to it from a clicked cell in a custom renderer. In the custom renderer you then update SelectedItem, which in turn highlights the row. SelectedItem must be set as TwoWay on your Grid, so you can update it from code..

**Comment by RaulLuna** [comment]
A lot of thanks, njale. I try it !!!
