### ISSUE TITLE
Dynamic value change update

### ISSUE THREAD

**Issue by srishalu** [akgulebubekir/Xamarin.Forms.DataGrid#129]
https://stackoverflow.com/questions/59321633/when-other-controls-is-placed-inside-datagrid-column-it-is-not-binding

Anyone faced this issue?

Thanks in advance

**Comment by akgulebubekir** [comment]
As far I understand you're adding an item to `Team` list and it does not appears in the grid. On this case **your list must be observable**. I suggets to make `Teams` to `ObservableCollection`
