### ISSUE TITLE
Tap event

### ISSUE THREAD

**Issue by ghost** [akgulebubekir/Xamarin.Forms.DataGrid#13]
Is it possible to register some method on tap event?
I was not able to find something like this.

**Comment by akgulebubekir** [comment]
Tap where?

**Comment by ghost** [comment]
If I click on my DataGridColumn/DataGridRow I want to do some action like open modal page with more details about object and etc.

**Comment by akgulebubekir** [comment]
SelectedRow property is available for row selection. If you want to add tap gesture into cell, you can override the cell template and add a button.

**Comment by sahithisk** [comment]
hii,i am trying to put navigation when certain column is clicked instead of any entire row in datagrid,but i could not getting the thing which iam looking for.could you please help in sorting out that.
thanks in advance.

**Comment by akgulebubekir** [comment]
Create a `TapGestureRecognizer` for your cells. Then listen the events.

**Comment by sahithisk** [comment]
Could u please send me the syntax for it....

**Comment by sahithisk** [comment]
</dg:DataGrid.HeaderFontSize>
                        <dg:DataGrid.Columns>
                            <dg:DataGridColumn Title="CustmorName" PropertyName="CustmorName" Width="2.4*">
                                <dg:Datagrid.CellTemplete>
<// how to add TapGestureRecognizer here
<dg:Datagrid.CellTemplete>
                            </dg:DataGridColumn>
                            <dg:DataGridColumn Title="Status" PropertyName="Status" Width="1.3*" >                                
                            </dg:DataGridColumn>
                            <dg:DataGridColumn Title="Date of visit" PropertyName="Date"  Width="2*" />
                            <dg:DataGridColumn Title="Village" PropertyName="Village" Width="1.5*"/>
                        </dg:DataGrid.Columns>

**Comment by akgulebubekir** [comment]
```
<dg:DataGrid.CellTemplate>
	<DataTemplate>
		<ContentView>
			<ContentView.GestureRecognizers>
				<TapGestureRecognizer/>
			</ContentView.GestureRecognizers>
			<Label Text="Column1"/>
		</ContentView>
	</DataTemplate>
</dg:DataGrid.CellTemplate>


```

**Comment by Manikmca10** [comment]
hi @akgulebubekir ,
i have tried in as you mentioned syntax,
like

<dg:DataGridColumn Title="OTML No" PropertyName="OTMLID" Width="70" SortingEnabled="False">
                            

                        <dg:DataGridColumn.CellTemplate>
                            <DataTemplate>
                                <ContentView>
                                    <ContentView.GestureRecognizers>
                                        <TapGestureRecognizer Command="{Binding TapCommand}"/>
                                    </ContentView.GestureRecognizers>
                                    <Label Text="OTMLID"/>
                                </ContentView>
                            </DataTemplate>
                        </dg:DataGridColumn.CellTemplate>

                    </dg:DataGridColumn>

and my view model like,
  public ICommand TapCommand { get; set; }
  private void CmdTap()
        {
            CCListDatabaseOperations objcclOp = new CCListDatabaseOperations();
           Teams = objcclOp.GetSearchList(OTML_ID_Number, Name);
           

        }

But Tap Event not fired
