### ISSUE TITLE
Header Title not visible at iOS

### ISSUE THREAD

**Issue by Doxoh** [akgulebubekir/Xamarin.Forms.DataGrid#136]
Hey,

I created a DataGrid in C# and the titles will shown in Android but in iOS it is blank.
Can someone help me?

![grafik](https://user-images.githubusercontent.com/17340739/84921669-12e0f500-b0c5-11ea-9927-4ca2ebb6815e.png)

Second question, is it possible to set the titles to center alignment?

Kind Regards
Doxoh

**Comment by akgulebubekir** [comment]
Hi,
It might be related with Dark/Light mode. If you override  `HeaderLabelStyle` you will get a foreground color. You can also set the header orentation with the style.

```
			<dg:DataGrid.HeaderLabelStyle>
				<Style TargetType="Label">
					<Setter Property="TextColor" Value="Orange"/>
					<Setter Property="HorizontalTextAlignment" Value="Center"/>
				</Style>
			</dg:DataGrid.HeaderLabelStyle>
```
