### ISSUE TITLE
Problem in Binding Data

### ISSUE THREAD

**Issue by babakmdi** [akgulebubekir/Xamarin.Forms.DataGrid#139]
Hello sir, I have api data, and i want show my data in data grid , 

its my code

   var deserializedProduct = JsonConvert.DeserializeObject<List<Ninja.Example>>(SS, settingss);
    Mygrid.ItemsSource = deserializedProduct;

and its my xaml : 

<dg:DataGrid.Columns>
            <dg:DataGridColumn  Width="100">
                <dg:DataGridColumn.CellTemplate>
                    <DataTemplate>
                        <StackLayout>
                            <Label Text="{Binding deserializedProduct.country}"    TextColor="Black" />
                        </StackLayout>
                    </DataTemplate>
                </dg:DataGridColumn.CellTemplate>
            </dg:DataGridColumn>

but its not working .

**Comment by Ayis1** [comment]
You need to assign a title and a property to each column. Title will be what reads in the header of the column and property refers to the field on your model. So if ninjas had a field called `public string name get; set; `you would have to put name as your property for that column.

To define a column use the following code:
```
                        <dg:DataGrid.Columns>
                            <dg:DataGridColumn Title="Ninja name" PropertyName="Name" Width="1*"/>
                            <dg:DataGridColumn Title="OtherName" PropertyName="OtherField" Width="*"/>
                             <!--Do the same for as many columns as  you would like -->
                        <dg:DataGrid.Columns/>
```
