### ISSUE TITLE
How to fire command of button inside DataGrid row?

### ISSUE THREAD

**Issue by Yuan-Ruby-Lp** [akgulebubekir/Xamarin.Forms.DataGrid#140]
**Model:**

  public class MainViewModel
    {

        public MainViewModel()
        {
            AuthorizeCommand = new Command<string>(CmdAuthorize);
        }

        public ICommand AuthorizeCommand { get; set; }
        public List<User> Users { get; set; }

       private void CmdAuthorize(string id)
        {
            var user = Users.First(x => x.Id == id);
        }
    }
   public class User
    {     
         public string Name { get; set; }
         public string Id { get; set; }   
    }
**Binding:**

 var model= new MainViewModel();
 model.Users = new List<User>();
 model.Users.Add(new User() {
    Name="A",
    Id ="1"  
   });
 model.Users.Add(new User()
  {
     Name = "B",
      Id = "2"
    });
 this.BindingContext = model;
             
      <dg:DataGrid.Columns>       
        <dg:DataGridColumn Title="Name" PropertyName="Name" Width="2*"/>
        <dg:DataGridColumn Title="Ip" PropertyName="Ip" Width="2*"/>
        <dg:DataGridColumn Title="Action"  Width="6*">
          <dg:DataGridColumn.CellTemplate>
              <DataTemplate>
                  <Button Text="Authorize" Clicked="" Command="{Binding AuthorizeCommand,Source={x:Reference self}}" CommandParameter="{Binding .}"/>
            </DataTemplate>            
          </dg:DataGridColumn.CellTemplate>
        </dg:DataGridColumn>
      </dg:DataGrid.Columns>
    </dg:DataGrid>

**Comment by Yuan-Ruby-Lp** [comment]
I  can't fire command of button inside the DataGrid, Maybe I use the wrong way,But how to resolve it?

**Comment by akgulebubekir** [comment]
```
<dg:DataGrid x:Name="self" ... >
	<dg:DataGrid.Columns>
		<dg:DataGridColumn Title="Details" PropertyName="." SortingEnabled="False">
			<dg:DataGridColumn.CellTemplate>
				<DataTemplate>
					<Button Text="Details" 
						Command="{Binding BindingContext.YourCommand, Source={x:Reference self}}" 
						CommandParameter="{Binding}" />
				</DataTemplate>
			</dg:DataGridColumn.CellTemplate>
		</dg:DataGridColumn>
	</dg:DataGrid.Columns>
</dg:DataGrid>
```
