### ISSUE TITLE
Resize column-headers and columns

### ISSUE THREAD

**Issue by Ayis1** [akgulebubekir/Xamarin.Forms.DataGrid#142]
Any plans for an implementation that allows us to resize grid columns on runtime? 

For instance if i have a column called description, but the description is so long that it doesn't fit in it's column, it would be nice to be able to drag column-headers and adjust the size of the column.

**Comment by Ayis1** [comment]
Or what other options do i have if i know my text in a given column potentially won't fit everytime?

**Comment by Ayis1** [comment]
Whats the reason you wont allow me to call HasUnevenRows? ..

**Comment by akgulebubekir** [comment]
you can re-set `Columns` property with a new ColumnCollection, and specify `Width`

**Comment by PontusHolmberg** [comment]
> you can re-set `Columns` property with a new ColumnCollection, and specify `Width`

I just tried that, only the header cell got resized.
