### ISSUE TITLE
Removing columns using code-behind results in column titles being removed but not the columns themselves.

### ISSUE THREAD

**Issue by iamleeg** [akgulebubekir/Xamarin.Forms.DataGrid#145]
I'm trying to create a configurable DataGrid where users can enable/disable display of any columns. Given the discussion in #143, I'm doing this by building a new `ColumnCollection` and replacing the `Columns` on the grid. If the new collection contains a subset of the previous collection, then the column titles are updated to reflect the new collection's contents but all of the data that was previously shown on the grid is still shown.

**Comment by iamleeg** [comment]
I have a workaround: at the time that I want to change the columns, I remove the `ItemsSource` and set it again (to the same object).

**Comment by akgulebubekir** [comment]
You have to create a new `ColumnCollection` instead clearing and re-adding columns one by one because of `ColumnCollection` is Not `ObservableCollection`.
