### ISSUE TITLE
When binding to ObservableCollection, after executing collection Clear() method ActiveRowColor not working anymore

### ISSUE THREAD

**Issue by wgarroyo** [akgulebubekir/Xamarin.Forms.DataGrid#147]
Binding the datagrid to an ObservableCollection<object>, the grid gets populated properly and ActiveRowColor works fine. But after calling Clear() method from the ObservableCollection, ActiveRowColor stops working in the ui (no higligthed color for selected row).

many thanks in advance

Regards

Example:
private readonly IAccountService _accountService;

public AccountListViewModel(IAccountService accountService, INavigationService navigationService, IPageDialogService dialogService)
            : base(navigationService, dialogService)
        {
            _accountService = accountService;
            SearchCommand = new Command(async () => await SearchAsync());
            Accounts = new ObservableCollection<AccountDto>();
        }

 public ICommand SearchCommand { private set; get; }

private async Task SearchAsync()
        {
            **Accounts.Clear();**
            Accounts.Add(new AccountDto());
        }

**Comment by Kingdom-Of-Heaven** [comment]
Have you resolved the issue?

**Comment by akgulebubekir** [comment]
Since you've cleared the DataSource there is nothing to select. Therefore you have to set `SelectedItem` property on your code.  I will close this since its not actually a bug.
