### ISSUE TITLE
It cannot center long texts

### ISSUE THREAD

**Issue by FANMixco** [akgulebubekir/Xamarin.Forms.DataGrid#155]
I'm building an app with 3 columns but two of them have long texts:

```xml
<dg:DataGrid.Columns>
    <dg:DataGridColumn
        Title="Month"
        PropertyName="Month"
        HorizontalContentAlignment="CenterAndExpand"
        VerticalContentAlignment="CenterAndExpand"
        Width="*"/>
    <dg:DataGridColumn
        x:Name="ColCurrentYear"
        VerticalContentAlignment="CenterAndExpand"
        HorizontalContentAlignment="CenterAndExpand"
        Title="2021 Consumption kWh"
        PropertyName="CurrentYear"
        Width="*"/>
    <dg:DataGridColumn
        x:Name="ColLastYear"
        VerticalContentAlignment="CenterAndExpand"
        HorizontalContentAlignment="CenterAndExpand"
        Title="2020 Consumption kWh"
        PropertyName="PreviousYear"
        Width="*"/>
</dg:DataGrid.Columns>
```

Then, it looks like this:

![Screenshot_1623917796](https://user-images.githubusercontent.com/1666156/122359020-7b231a80-cf55-11eb-9041-fa1aaea65cf9.png)

I tried without the \r\n and the result was the same. I found that in Android you can use this to force the centering: `HorizontalTextAlignment="Center"` because it seems this is a Xamarin.Forms bug thatI I reported.

**Comment by akgulebubekir** [comment]
You can use LineWrapping option for Column in latest release
