### ISSUE TITLE
CellTemplate binding issue

### ISSUE THREAD

**Issue by mehtaperdal** [akgulebubekir/Xamarin.Forms.DataGrid#16]
Datagrid's `BindingContext `doesn't work in `CellTemplate`!

When I set CellTemplate and BindingContext of a DataGridCell, I expect to bind that context and show data regarding that, but it doesn't.

**Comment by akgulebubekir** [comment]
Invalid request, yet it seems unnecessary. There is no `Property `or `class `named `DataGridCell`. However when you use default template(a single `Label `in cell) it binds automatically.
