### ISSUE TITLE
MAUI Support

### ISSUE THREAD

**Issue by inforithmics** [akgulebubekir/Xamarin.Forms.DataGrid#168]
Is there Interest in MAUI Support. (Pull Request with different Project File but Same Code (with Conditional Compiles)).

The new nuget would be Maui.DataGrid.

(Nothing done yet only for asking what the plans are).

**Comment by akgulebubekir** [comment]
I'm plannig to start the implementation soon

**Comment by AathifMahir** [comment]
> I'm plannig to start the implementation soon

I could help with porting for Maui, let me know if you're interested we can plan ahead

**Comment by akgulebubekir** [comment]
https://github.com/akgulebubekir/Maui.DataGrid
