### ISSUE TITLE
Styling of sorting icons

### ISSUE THREAD

**Issue by mehtaperdal** [akgulebubekir/Xamarin.Forms.DataGrid#17]
Sorting icons' sizes are too small. Please add icon style property.

**Comment by akgulebubekir** [comment]
Please use `AscendingIconStyle `& `DescendingIconStyle ` properties for that purpose.

**Comment by mehtaperdal** [comment]
Thanks. When will you update nuget package?

**Comment by akgulebubekir** [comment]
released as beta([here](https://www.nuget.org/packages/Xamarin.Forms.DataGrid/1.7.0-beta1))
