### ISSUE TITLE
Selection does not work with the new nuget

### ISSUE THREAD

**Issue by thomasstockermc** [akgulebubekir/Xamarin.Forms.DataGrid#170]
In this Version selection does not work:
https://www.nuget.org/packages/Xamarin.Forms.DataGrid/5.0.0.2515

In the DataGrid.xaml
following has to be changed:
`<CollectionView x:Name="_collectionView" ItemTemplate="{StaticResource RowTemplateSelector}"  />`
To:
`<CollectionView x:Name="_collectionView" ItemTemplate="{StaticResource RowTemplateSelector}" SelectionMode="Single" />`

Then the selection works. 
The Default of the SelectionMode is None.

**Comment by thomasstockermc** [comment]
Maybe a Selction Mode Property has to be made to specify the Selection mode on the Underlaying CollectionView

**Comment by TheR7angelo** [comment]
Hi i have the same problem.
Just downgrade and it'works.
The problem is related with the ListViewCachingStrategy with the new nuget.
