### ISSUE TITLE
Hide the column in the DataGridColumn

### ISSUE THREAD

**Issue by JayashreePrabakaran** [akgulebubekir/Xamarin.Forms.DataGrid#177]
I need to hide the entire column of chip index column
![image](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/assets/87711454/166cadaf-4f63-4b4f-995b-2d00d17c9815)

![f6a37118-d671-453e-9cf4-4935ee2a91c0](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/assets/87711454/711c8269-3235-4559-89c4-385a557d643a)

**Comment by akgulebubekir** [comment]
you can bind bind columns to a collection of `DataGridColumn`. Removing it from the collection will remove it from the UI as well.
