### ISSUE TITLE
Any Support for MAUI

### ISSUE THREAD

**Issue by NiladriPadhy** [akgulebubekir/Xamarin.Forms.DataGrid#178]
We have used Xamarin.Forms.DataGrid plugin in our Xamarin project. We are in a phase of migraring the xamarin project to MAUI. Any roadmap to extend the Support for MAUI.

**Comment by akgulebubekir** [comment]
Please use [Maui.Datagrid](https://github.com/akgulebubekir/Maui.DataGrid) for Maui applications
