### ISSUE TITLE
Goto to specified row

### ISSUE THREAD

**Issue by giaza** [akgulebubekir/Xamarin.Forms.DataGrid#2]
Is there a way to go to a specified row having a large dataset?

**Comment by akgulebubekir** [comment]
Hi,

if you mean creating a row with a different template, no its not supporting that :( But you can customize rows as you want(you can even create two line rows) with DataTemplates.

**Comment by akgulebubekir** [comment]
Hi, 
what do you mean by going to specified row having a large dataset ?

**Comment by giaza** [comment]
Hi,
Thank you for your answer. 
I have a list with a date field and others.
I would like to show this list with your control but i would also like that  the datagrid was positioned  on  the record with the date of  today without filtering.
Is this possible?
This data represent a calendar of events and I want to show the events of  today first, but I want to show them all.
Thanks in advance.

**Comment by akgulebubekir** [comment]
Hi again,

it does not supports auto sorting, but I'm planning to add it.

**Comment by giaza** [comment]
Hi thanks for your help.
I guess I can filter out all events prior today and show today event as first.
Just another question.
You said I can use a data template to achieve complex layouts, even have two rows per item.
Do you have an example of doing this by code?
I am fairly new to xamarin.

**Comment by akgulebubekir** [comment]
``` Xaml
        <dg:DataGridColumn Title="Stock" PropertyName="StockInfo" Width="*">
          <dg:DataGridColumn.CellTemplate>
            <DataTemplate>
              <Grid>
                <Grid.RowDefinitions>
                  <RowDefinition Height="*"/>
                  <RowDefinition Height="*"/>
                </Grid.RowDefinitions>
                <Label Text="{Binding ItemName}" HorizontalOptions="Center" VerticalOptions="Center" TextColor="Black"/>
                <Label Grid.Row="1" Text="{Binding Amount}" HorizontalOptions="Center" VerticalOptions="Center" TextColor="Black"/>
              </Grid>
            </DataTemplate>
          </dg:DataGridColumn.CellTemplate>
        </dg:DataGridColumn>
```

**Comment by giaza** [comment]
Thank you so much!

Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Ebubekir Akgül notifications@github.com
Data:
A: "akgulebubekir/Xamarin.Forms.DataGrid" Xamarin.Forms.DataGrid@noreply.github.com
Cc: Gianmichele Zanelli giaza@hitekno.it,Author author@noreply.github.com
Oggetto: Re: [akgulebubekir/Xamarin.Forms.DataGrid] Goto to specified row (#2)

```
    <dg:DataGridColumn Title="Stock" PropertyName="StockInfo" Width="*">
      <dg:DataGridColumn.CellTemplate>
        <DataTemplate>
          <Grid>
            <Grid.RowDefinitions>
              <RowDefinition Height="*"/>
              <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Label Text="{Binding ItemName}" HorizontalOptions="Center" VerticalOptions="Center" TextColor="Black"/>
            <Label Grid.Row="1" Text="{Binding Amount}" HorizontalOptions="Center" VerticalOptions="Center" TextColor="Black"/>
          </Grid>
        </DataTemplate>
      </dg:DataGridColumn.CellTemplate>
    </dg:DataGridColumn>
```

**Comment by karanshinde8282** [comment]
have u found anything for this
i am also working on it but no any solution found
please let me know if u found any solution
Thanks
