### ISSUE TITLE
Align header 

### ISSUE THREAD

**Issue by MonikaHencekova** [akgulebubekir/Xamarin.Forms.DataGrid#22]
I need to align header depending to column, so when I have 2 items in header and 2 columns, columns are align to left and right side I want to do the same with header items. Is it possible?

**Comment by akgulebubekir** [comment]
Hi,

Currently we don't have that feature, and it seem you cannot have workaround with converters.  I'll  add that feature ASAP.

**Comment by akgulebubekir** [comment]
Fixed in [1.8.0-pre1](https://www.nuget.org/packages/Xamarin.Forms.DataGrid/1.8.0-pre1)

**Comment by MonikaHencekova** [comment]
Thanks for adding this settings
