### ISSUE TITLE
Sort event is not working properly

### ISSUE THREAD

**Issue by SyedMuhammadYasir** [akgulebubekir/Xamarin.Forms.DataGrid#25]
I have bind a list with a datatime column, sort event is not working correct on that particular column. I have attach a screen shot.
![image](https://cloud.githubusercontent.com/assets/25895840/23116360/018baa90-f76c-11e6-94e5-3c3989a3a956.png)

**Comment by akgulebubekir** [comment]
Hi,

it seems sorted correctly by descending. I couldn't get the issue that you've been faced.  Could you please explain detailed?

**Comment by akgulebubekir** [comment]
Closing this thread. Not a bug @SyedMuhammadYasir
