### ISSUE TITLE
Binding ItemsSource to ObservableCollection<T> doesn't work.

### ISSUE THREAD

**Issue by adaml984** [akgulebubekir/Xamarin.Forms.DataGrid#27]
Hello,
After binding ObservableCollection<T> to ItemsSource I cannot see my data.
On the other hand binding to List<T> works fine.
I've found part of code which I believe causes binding problem (from dataGrid.xaml.cs):
`
//ObservableCollection Tracking 
					if (n is INotifyCollectionChanged)
						(n as INotifyCollectionChanged).CollectionChanged += (list, arg) =>
						{
							if (list == (b as DataGrid).ItemsSource && self._listView.ItemsSource != list)
								self.SortItems(self.SortedColumnIndex, false);
						};
					else
					{
						self._listView.ItemsSource = n as IEnumerable;
						if (self.IsSortable && self.SortedColumnIndex >= 0)
							self.SortItems(self.SortedColumnIndex, false);
					}
`
Best regards,
Adam

**Comment by assemhakmeh** [comment]
I've encountered this issue before. I'm going to submit a pull request with a solution. The DataGrid needs to maintain a internal indexed list to facilitate sorting/grouping and index lookups for items during the render phase.

**Comment by adaml984** [comment]
I think putting else clause around code that assigns collection to listview's ItemsSource is unnecessary.
