### ISSUE TITLE
Data template in a column in c#

### ISSUE THREAD

**Issue by PlusInf0Iulia** [akgulebubekir/Xamarin.Forms.DataGrid#32]
Hello everybody.
I've added this grid to my project and i use it from C# programmatically.
Everything work fine but when i want to set a data template it doesn't work anymore.
This is my data grid:
```
public class myDataGrid: ScrollView
	{
		public DataGrid grid;
		public string _queriesId;
		public myDataGrid(string queryId )
		{
			System.Diagnostics.Debug.WriteLine("myDataGrid - costructor queryId: " + queryId);
			_queriesId = queryId;
			grid = new DataGrid();
			grid.Columns = generateColumn();
			grid.BorderColor = GlobalVariables.BackColorGrigio1();
			grid.BackgroundColor = Color.White;
			grid.HeaderBackground = GlobalVariables.BackColorGrigioDark();
			grid.HeaderTextColor = Color.White;
			grid.HeaderBordersVisible = false;
			grid.SelectionEnabled = true;

			var pc = new PaletteCollection();
			pc.Add(GlobalVariables.TextColorGrigio1());
			grid.RowsTextColorPalette = pc;
			grid.HeaderHeight = 40;
			grid.ActiveRowColor = GlobalVariables.BackColorAzzurro1();
			grid.VerticalOptions = LayoutOptions.FillAndExpand;
			Orientation = ScrollOrientation.Horizontal;
			Content = grid;
			System.Diagnostics.Debug.WriteLine("myDataGrid - costructor end");
		}
		private ColumnCollection generateColumn()
		{

			System.Diagnostics.Debug.WriteLine("myDataGrid - generateColumn start");
			var columns = new ColumnCollection();
			var queries = QueriesListData.getQueryById(_queriesId);
//is a dictionary of dictionary where i have the name of the column of the table from DB and in the dictionary i have the configuration. When i have a date i want to set up the format but it can also be empty
			var fields = queries.qFieldsList;
			foreach (var field in fields)
			{
				if (field.Value["visible"] == "true")
				{
					var column = new DataGridColumn();
					column.Title = field.Value["headerText"];
					column.PropertyName = field.Key;
					if (field.Value["width"] != "*")
					{
						column.Width = int.Parse(field.Value["width"]);
					}
					if (field.Value["tipo"] == "data")
					{
						System.Diagnostics.Debug.WriteLine("myDataGrid - generateColumn tipo data");
						column.CellTemplate = new DataTemplate(() =>
						{
							var grr = new Grid();
							grr.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });

							var nameLabel = new Label { FontAttributes = FontAttributes.Bold,Text="ciao" };

							nameLabel.SetBinding(Label.TextProperty, field.Key);

							grr.Children.Add(nameLabel);

							return new ViewCell
							{
								View = grr
							};
						});




					}
					else {
						

						if (field.Value["tipo"] == "int")
						{
							column.HorizontalContentAlignment = LayoutOptions.EndAndExpand;
						}
						else if (field.Value["tipo"] == "double")
						{
							column.HorizontalContentAlignment = LayoutOptions.EndAndExpand;
						}
						else if (field.Value["tipo"] == "string")
						{
							column.HorizontalContentAlignment = LayoutOptions.StartAndExpand;
						}
					}
					columns.Add(column);
				}
			}

			System.Diagnostics.Debug.WriteLine("myDataGrid - generateColumn end");
			return columns;

		}
	}

```

**Comment by akgulebubekir** [comment]
Hi,

**Xamarin.Forms.DataGrid** has below update which changes your **_Cell_**'s `BindingContext`. Please consider that and if you still need assistance please provide us a sample project that the issue occurs.

- PropertyName bind to your cell's context now. Please consider this, if necessary kindly update your code.

**Comment by PlusInf0Iulia** [comment]
but even if i but a text fixed the datatemplate doesn't appear.

**Comment by akgulebubekir** [comment]
As I see from your code you cannot understand if `DataTemplate` appeared or not. You could check that by setting the `BackgroundColor` to a solid color

**Comment by PlusInf0Iulia** [comment]
even if i put the background color nothing happens. the datatemplate doesn't appear..

**Comment by Kasilingam1230** [comment]
I used the same like this, in generateColumn() as mention below 


        private ColumnCollection generateColumn()
        {

            var columns = new ColumnCollection();

            var dl = new DataGridColumn
            {
                Title = "Logo",
                PropertyName = "Logo",
                Width = 100,
                SortingEnabled = false,
                CellTemplate = new DataTemplate(() => {

               var logoLbl = new Image { Source = "{Binding Logo}", HorizontalOptions = LayoutOptions.Center, VerticalOptions = LayoutOptions.Center, Aspect = Aspect.AspectFit, HeightRequest = 60 };

                return new ViewCell
                {
                    View = logoLbl
                };

              })
            };

            columns.Add(dl);
            columns.Add(new DataGridColumn { Title = "Team", PropertyName = "Name", Width = GridLength.Star });
            columns.Add(new DataGridColumn { Title = "Win", PropertyName = "Win", Width = GridLength.Star });
            columns.Add(new DataGridColumn { Title = "Home", PropertyName = "Home", Width = GridLength.Star });
            columns.Add(new DataGridColumn { Title = "Percentage", PropertyName = "Percentage", Width = GridLength.Star });
            columns.Add(new DataGridColumn { Title = "Streak", PropertyName = "Streak", Width = GridLength.Star });
            return columns;
        }

I was unable to view Logo Column Values alone. How can I get values into it.

Thank You in advance.

**Comment by akgulebubekir** [comment]
You cannot use  something like **`Source = "{Binding Logo}"`** . This expression only works in Xaml.  If you want to do something like this try to use ResourceDictionary or templates as below : 

```
	<Application.Resources>
		<ResourceDictionary>
			<DataTemplate x:Key="LogoColumnTemplate">
				<Image Source="{Binding }" HorizontalOptions="Center" VerticalOptions="Center" Aspect="AspectFit" HeightRequest="60"/>
			</DataTemplate>
		</ResourceDictionary>
	</Application.Resources>
```

```
DataTemplate colTemplateFromXaml = App.Current.Resources["LogoColumnTemplate"] as DataTemplate;
DataTemplate colTempalteFromCs = new DataTemplate(() =>
					{
						var img = new Image()
						{
							HorizontalOptions = LayoutOptions.Center,
							VerticalOptions = LayoutOptions.Center,
							Aspect = Aspect.AspectFit,
							HeightRequest = 60
						};

						img.SetBinding(Image.BindingContextProperty, new Binding(""));
						return img;
					});

```

**Comment by Kasilingam1230** [comment]
I changed my code like the same as like you said in generateColumn(), but still I cannot get the First Column

    private ColumnCollection generateColumn()
    {

        var columns = new ColumnCollection();

        var dl = new DataGridColumn
        {
            Title = "Logo",
            PropertyName = "Logo",
            Width = 100,
            SortingEnabled = false
        };
        DataTemplate colTempalteFromCs = new DataTemplate(() =>
        {
                var img = new Image()
                {
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    Aspect = Aspect.AspectFit,
                    HeightRequest = 60
                };

                img.SetBinding(Image.BindingContextProperty, new Binding("Logo"));
                return img;
        });

        dl.CellTemplate = colTempalteFromCs;

        columns.Add(dl);
        columns.Add(new DataGridColumn { Title = "Team", PropertyName = "Name", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Win", PropertyName = "Win", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Home", PropertyName = "Home", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Percentage", PropertyName = "Percentage", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Streak", PropertyName = "Streak", Width = GridLength.Star });
        return columns;
    }

and I tried using Label instead of Image, but I was unable to view the Column Value again.

    private ColumnCollection generateColumn()
    {

        var columns = new ColumnCollection();

        var dl = new DataGridColumn
        {
            Title = "Logo",
            PropertyName = "Logo",
            Width = 100,
            SortingEnabled = false
        };
        DataTemplate colTempalteFromCs = new DataTemplate(() =>
        {
                var nameLabel = new Label();
                nameLabel.SetBinding(Label.TextProperty, new Binding("Logo"));
                return nameLabel;
        });

        dl.CellTemplate = colTempalteFromCs;

        columns.Add(dl);
        columns.Add(new DataGridColumn { Title = "Team", PropertyName = "Name", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Win", PropertyName = "Win", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Home", PropertyName = "Home", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Percentage", PropertyName = "Percentage", Width = GridLength.Star });
        columns.Add(new DataGridColumn { Title = "Streak", PropertyName = "Streak", Width = GridLength.Star });
        return columns;
    }

**Comment by akgulebubekir** [comment]
replace `new Binding("Logo"))` with `new Binding(""))`

**Comment by Kasilingam1230** [comment]
Tried that one too, I got an exception as "path can not be an empty string Parameter name: path" while using : nameLabel.SetBinding(Label.TextProperty, new Binding(""));

**Comment by Kasilingam1230** [comment]
Tried that one too, I got an exception as "path can not be an empty string Parameter name: path" while using : 

       nameLabel.SetBinding(Label.TextProperty, new Binding(""));

**Comment by Kasilingam1230** [comment]
Still I was unable to fix the above issue.

Tried that one too, I got an exception as "path can not be an empty string Parameter name: path" while using :

   nameLabel.SetBinding(Label.TextProperty, new Binding(""));

If anyone knows help me & Thank you in advance.

**Comment by assemhakmeh** [comment]
Hello,

You can try to use a "." instead of an "" for the binding path.


Assem Hakmeh

Prothion Inc.

**Comment by Kasilingam1230** [comment]
Fixed...
I tried to use a "." instead of an "" for the binding path.

Thank you  assemhakmeh

**Comment by Sumit2668** [comment]
Not Refreshing Xamarin.Forms.DataGrid List.
I am using to Xamarin.Forms.DataGrid plugins and create a dynamic column in C#, I am retrieving data on monthly wise 3,6,12 months.
but the first time is successfully showing data and then press next button, this time only columns changes.
what can I do Plz help me ... :(

**Comment by Sumit2668** [comment]
How to add grid.ItemSelected in C#

**Comment by deepakmagic90** [comment]
I want to retrieve data in c# code. can  any one help me.

  <dg:DataGrid  x:Name="dg_LeaveList"  SelectionEnabled="True" 
               RowHeight="40" HeaderHeight="40" BorderColor="#CCCCCC" HeaderBackground="#E0E6F8" >
                    <dg:DataGrid.HeaderFontSize>
                        <OnIdiom  x:TypeArguments="x:Double">
                            <OnIdiom.Tablet>15</OnIdiom.Tablet>
                            <OnIdiom.Phone>13</OnIdiom.Phone>
                        </OnIdiom>
                    </dg:DataGrid.HeaderFontSize>
                    <dg:DataGrid.Columns>
                        <dg:DataGridColumn Title="Date" PropertyName="DDate" Width="80"/>

                        <dg:DataGridColumn Title="LeaveCode" PropertyName="LeaveCode" Width="100">
                            <dg:DataGridColumn.CellTemplate>
                                <DataTemplate>
                                    <Picker Title="Code" FontSize="12"  SelectedItem="{Binding LeaveCode}">
                                        <Picker.ItemsSource>
                                            <x:Array Type="{x:Type x:String}">
                                                <x:String></x:String>
                                                <x:String>LEAVE</x:String>
                                                <x:String>OD</x:String>
                                                <x:String>WFH</x:String>
                                            </x:Array>
                                        </Picker.ItemsSource>                                       
                                    </Picker>
                                    
                                </DataTemplate>
                            </dg:DataGridColumn.CellTemplate>
                        </dg:DataGridColumn>

                        <dg:DataGridColumn Title="LeaveType" PropertyName="LeaveType" Width="100">
                            <dg:DataGridColumn.CellTemplate>
                                <DataTemplate>
                                    <Picker Title="Type" FontSize="12"  SelectedItem="{Binding LeaveType}">
                                        <Picker.ItemsSource>
                                            <x:Array Type="{x:Type x:String}">
                                                <x:String></x:String>
                                                <x:String>Quarter</x:String>
                                                <x:String>Half Day</x:String>
                                                <x:String>Three Fourth</x:String>
                                                <x:String>Full Day</x:String>
                                            </x:Array>
                                        </Picker.ItemsSource>
                                    </Picker>                                    
                                </DataTemplate>
                            </dg:DataGridColumn.CellTemplate>
                        </dg:DataGridColumn>
                        
                        <dg:DataGridColumn Title="Remark" PropertyName="Reason" Width="120">
                            <dg:DataGridColumn.CellTemplate>
                                <DataTemplate>
                                    <Editor x:Name="txtReason" AutoSize="TextChanges" FontSize="12" Margin="0"  />
                                </DataTemplate>
                            </dg:DataGridColumn.CellTemplate>
                        </dg:DataGridColumn>
                        
                    </dg:DataGrid.Columns>
                    <dg:DataGrid.RowsBackgroundColorPalette>
                        <dg:PaletteCollection>
                            <Color>#F2F2F2</Color>
                            <Color>#FFFFFF</Color>
                        </dg:PaletteCollection>
                    </dg:DataGrid.RowsBackgroundColorPalette>
                   
                </dg:DataGrid>
