### ISSUE TITLE
Binding to List<T>

### ISSUE THREAD

**Issue by bleekbless** [akgulebubekir/Xamarin.Forms.DataGrid#33]
When I try to use { Binding SomeAttribute } it doesn't work
 `.<dg:DataGridColumn Title="Detalhar" Width="2*" PropertyName="Cor" >
        <DataTemplate>
          <Button BorderColor="Gray"  Text="{Binding Cor}" />
        </DataTemplate>
      </dg:DataGridColumn>`

**Comment by akgulebubekir** [comment]
Hi,

I need detailed information about your issue:

- Which version are you using
- What is your data Type(i.e. `List<MyObject>` including properties of the `MyObject`) 
- Could you please shere detailed codepiece?

**Comment by bleekbless** [comment]
I'm using the latest version, properties of MyObject are only strings.

`    
public class Frequencia
    {
        public string Disc { get; set; }
        public string TotalAulas { get; set; }
        public string AulasDadas { get; set; }
        public string Faltas { get; set; }
        public string FaltasPermitidas { get; set; }
        public string PorcentagemFaltasTotal { get; set; }
        public string PorcentagemFaltasDadas { get; set; }
        public string Cor { get; set; }
    }
`

**Comment by akgulebubekir** [comment]
Since 1.8.7 binds the property name you shouldn't bind **Cor** again.

i.e: 

```xaml
	<dg:DataGridColumn Title="Detalhar" Width="2*" PropertyName="Cor" >
		<dg:DataGridColumn.CellTemplate>
			<DataTemplate> 
				<Button BorderColor="Gray" Text="{Binding .}" /> 
			</DataTemplate> 
		</dg:DataGridColumn.CellTemplate>
	</dg:DataGridColumn>
```
