### ISSUE TITLE
Background Color Update

### ISSUE THREAD

**Issue by sgaumont** [akgulebubekir/Xamarin.Forms.DataGrid#36]
Great control, thanks for your hard work. Unfortunately, I am having an issue where the selected row's background color is not being updated on click/tap. However, if I select it then re-sort, modify my bound list, etc it will then correctly update and change the background color of the previously selected row.

I poked around in the code but couldn't see anything obvious. Any thoughts?

**Comment by akgulebubekir** [comment]
Hi,

Which platforms are you using?

**Comment by sgaumont** [comment]
UWP.

**Comment by sushibear** [comment]
I second this bug on UWP!
Selecting a row does NOT update the rows background color after selection. Only if you re-sort, the updated color will be displayed properly.

**Comment by akgulebubekir** [comment]
Should be fixed with 3.0.0-pre1 package
