### ISSUE TITLE
Binding Columns Bug

### ISSUE THREAD

**Issue by KSemenenko** [akgulebubekir/Xamarin.Forms.DataGrid#39]
Hi, Thank you very much for your wonderful control.
I found a bug that occurs when Binding to Columns property.
This is NullReferenceException.
In this file:
[DataGrid.xaml.cs](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/blob/master/Xamarin.Forms.DataGrid/DataGrid.xaml.cs#L451) Columns in null
To repair, I added checks for null
```cs
if(Columns == null)
{
    return;
}

foreach (var col in Columns)
{......
```
Before foreach.
and it worked)))

**Comment by akgulebubekir** [comment]
`Colums `property will be `null `untill binds. 

I'll close because this is not a real issue.

**Comment by KSemenenko** [comment]
No, it's real issue. If you call InitHeaderView() when Colums equals null, you have a crash.
