### ISSUE TITLE
Please add an ItemSelected event

### ISSUE THREAD

**Issue by rvanderkooy** [akgulebubekir/Xamarin.Forms.DataGrid#4]
An ItemSelected event would be beneficial as this can be used to wire up additional commands to respond to selection.

I have these changes available if you will accept pull requests.

**Comment by akgulebubekir** [comment]
Added ([here](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/commit/3be3258c30e40d9268cd30991281f4adc7394569))
