### ISSUE TITLE
Height of grid inside a ScrollView

### ISSUE THREAD

**Issue by claesl** [akgulebubekir/Xamarin.Forms.DataGrid#40]
Hi,
I have placed two DataGrid's inside a StackLayout which in located in a ScrollView.
On iOS everything looks normal when when using Android I get a large bottom padding that I cannot understand.
Both grids have this problem. Strange thing is that the second DataGrid seems to get about the double amount of bottom margin as the first.

<StackLayout>

<ScrollView BackgroundColor="#CC000000">
   <StackLayout  Padding="4" Spacing="2"  >
      <dg:DataGrid ItemsSource="{Binding ScoreBoard.MyRuns}" 
                                     IsEnabled="false"
                                     BackgroundColor="Transparent" 
                                     HeaderBackground="Transparent" 
                                     BorderColor="Transparent" 
                                     BorderThickness="-1"
                                     IsSortable="false" Margin="0" Padding ="0"
                                     SelectionEnabled="false"
                                     HeaderTextColor="White"
                                     ActiveRowColor="Transparent"
                                     RowHeight="26"
                                     HeaderBordersVisible="false">
         <dg:DataGrid.Columns>
          ...
         </dg:DataGrid.Columns>

         <dg:DataGrid.RowsBackgroundColorPalette>
                 <dg:PaletteCollection>
                        <Color>#222</Color>
                        <Color>#333</Color>
                 </dg:PaletteCollection>
         </dg:DataGrid.RowsBackgroundColorPalette>
      </dg:DataGrid>
   </StackLayout>
 </ScrollView>

</StackLayout>

Any ideas or do you need more details?

**Comment by claesl** [comment]
Found the problem myself :)
It was how data was loaded which caused this somehow.

But now my problem is that I load data in OnAppearing on the view and set the property that DataGrid is binded to but it will not update the grid. I have to force a refresh of the DataGrid somehow...

**Comment by claesl** [comment]
The Binding does not update when changing content in OnAppearing. All other binded properties are updated but not the DataGrid. No reaction of RaisePropertyChanged for MVVM.

If I reopen the view again it will show the data from before even if it loads new data when opening.

If if have the data source set to null and then set it in the OnAppearing it will show but then the sizing is really strange. Datagrid is much larger in height than actual content is.

Is ItemSource not binded to be updated?

**Comment by jevonpack** [comment]
@claesl I'm having this same issue and I'm loading the data either in OnAppearing or later on through a button click. How were you able to get the height issue to disappear after loading the data?
