### ISSUE TITLE
Sorting Image Bug

### ISSUE THREAD

**Issue by rickrvo** [akgulebubekir/Xamarin.Forms.DataGrid#41]
The Sorting image for indicatin ascending or descending order only appears the first time you click on a column.
If you order by one column and then order by a different column the arrow image won't appear on that new column. If you order by the first column again the ordenation works but the arrow image will never appear again on any column. Only works the first time a column is selected.
I even tried progamatically trying to clear the datagrid but still no arrow. Something like:
                dataGrid.ItemsSource = null;
                dataGrid.IsSortable = false;
                dataGrid.ItemsSource = OrderList;
                dataGrid.IsSortable = true;
                dataGrid.ForceLayout();

**Comment by akgulebubekir** [comment]
Please use [1.9.3](https://www.nuget.org/packages/Xamarin.Forms.DataGrid/1.9.3) version

**Comment by rickrvo** [comment]
Thank you! It works. 
Now I just need to know how do I clear the sorting image?
If I update the table I want to be able to erase the image and only appear again if feild is tapped.
