### ISSUE TITLE
.NETStandard support

### ISSUE THREAD

**Issue by dbyrdomniware** [akgulebubekir/Xamarin.Forms.DataGrid#42]
It appears that this library is not supported with .NETStandard, is there any workaround? I installed the package as it was described in the README for this NuGet package for all the Xamarin.Forms platform-specific (iOS, Android, UWP) projects and then added Xamarin.Forms.DataGrid.dll as a reference to the .NETStandard project, but I am still getting a runtime error when I try to access the XAML page with the data grid on it. The error is very generic - just an unhandled exception occurred.

**Comment by akgulebubekir** [comment]
Please be sure calling `Xamarin.Forms.DataGrid.DataGridComponent.Init()` before using from Xaml

**Comment by enryb** [comment]
It seems to properly work with .NET standard 2.0, but at compiling time you have this warning:
5>***mypath***.csproj : warning NU1701: Il pacchetto 'Xamarin.Forms.DataGrid 1.9.6' è stato ripristinato mediante '.NETFramework,Version=v4.6.1' e non mediante il framework di destinazione del progetto '.NETStandard,Version=v2.0'. Questo pacchetto potrebbe non essere completamente compatibile con il progetto.
That means "packet Xamarin.Forms.DataGrid 1.9.6 was restored with '.NETFramework,Version=v4.6.1' and not with target framework of the project '.NETStandard,Version=v2.0'. This package may not completely be compatible with the project.

**Comment by akgulebubekir** [comment]
Please check [1.9.7-pre1](https://www.nuget.org/packages/Xamarin.Forms.DataGrid/1.9.7-pre1) for .Net Standarts support
