### ISSUE TITLE
Active row not working on UWP

### ISSUE THREAD

**Issue by Kirenenko** [akgulebubekir/Xamarin.Forms.DataGrid#43]
I have tested ActiveRowColor attribute and it works in Android, but not in UWP. Are there any workarounds for this issue?

**Comment by sushibear** [comment]
Seems to be the same problem as described here: https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/issues/36

**Comment by akgulebubekir** [comment]
Should be fixed with 3.0.0-pre1 package
