### ISSUE TITLE
How to Clear DataGrid

### ISSUE THREAD

**Issue by NadirHussainDasti** [akgulebubekir/Xamarin.Forms.DataGrid#44]
Dear akgulebubekir
I am using the grid in my project and its working.I am stuck here on one point.I want to clear all the rows  and reload the data again.But i could not succeed.Sirens is my datasource.

           Sirens.Clear();
            Sirens = null;
            Sirens=new List<ClsSirensModel>();
                 
            foreach (Feature feature in _selectedFeatures)
            {
                 SirenObj = new ClsSirensModel();
                 SirenObj.Logo = "password.png";
                  Sirens.Add(SirenObj);
          }

           <dg:DataGrid x:Name="DataGrid" ItemsSource="{Binding Sirens}" SelectionEnabled="True" SelectedItem="{Binding SelectedSiren}" RowHeight="30" HeaderHeight="50" BorderColor="#CCCCCC" HeaderBackground="#E0E6F8" ActiveRowColor="#8899AA">

  <dg:DataGrid.Columns>
                    <dg:DataGridColumn Title="Region" PropertyName="RegionNameAr"  Width="2.0*"/>
 </dg:DataGridColumn>
                        <dg:DataGridColumn Title="Logo" VerticalContentAlignment="Center" PropertyName="Logo" Width="50" HorizontalContentAlignment="Center" SortingEnabled="False">
                          <dg:DataGridColumn.CellTemplate>
                              <DataTemplate>
                                <Image Source="{Binding}" HorizontalOptions="Center"  VerticalOptions="Center" Aspect="AspectFit" HeightRequest="60">
                                    <Image.GestureRecognizers>
                                        <TapGestureRecognizer Command="{Binding Path=BindingContext.TapCommand,Source={x:Reference DataGrid}}" CommandParameter="Logo" NumberOfTapsRequired="1">
                                          
                                        </TapGestureRecognizer>
                                    </Image.GestureRecognizers>
                                </Image>
                            </DataTemplate>
                             </dg:DataGridColumn.CellTemplate>
                          </dg:DataGridColumn>
                  </dg:DataGrid.Columns>
</dg:DataGrid>
but grid not clear.Please help.

Thanks in advance.

**Comment by akgulebubekir** [comment]
You should` ObservableCollection<T>` instead `List<T>`.
