### ISSUE TITLE
How to clear sorting image?

### ISSUE THREAD

**Issue by rickrvo** [akgulebubekir/Xamarin.Forms.DataGrid#45]
Thank you! Version 1.9.3 works. It solved my previous issue.
Now I just need to know how do I clear the sorting image?
If I update the datagrid I want to be able to erase the image and only appear again if feild is tapped.

**Comment by akgulebubekir** [comment]
set `SortedColumnIndex = null`

**Comment by rickrvo** [comment]
Setting SortedColumnIndex = null  throws an exception and I get a app crash.
