### ISSUE TITLE
Cannot scroll when it is inside a ScrollView. Any solutions?

### ISSUE THREAD

**Issue by HubKing** [akgulebubekir/Xamarin.Forms.DataGrid#46]
The structure is, ScrollView - StackLayout - DataGrid. The page has other views, so it is long. This is why I used a StackLayout to stack them. Since it is long, it needs to be scrolled. That is why I put the StackLayout inside a ScrollView.

I set the DataGrid's height to 300. When there are many items, I can see a scrollbar inside the DataGrid, but when I try to scroll it, the outer ScrollView scrolls, so I cannot view the bottom items of DataGrid.

Is there any solution? Or should I avoid using a ScrollView?

**Comment by assemhakmeh** [comment]
Generally having a ListView in a ScrollView will be problematic if both
scroll in the same direction.

You can try setting the
PlatformConfiguration.iOSSpecific.ScrollView.ShouldDelayContentTouchesProperty
on your parent ScrollView and see if that allows you to scroll the DataGrid
as expected. However, this may impact the interaction with other controls
in the ScrollView as the touches will passed to them immediately, so you
may end up clicking buttons when you actually intended to scroll.


Assem Hakmeh

Prothion Inc.
assemhakmeh@prothion.com
Mobile (514) 995-5452
Office (514) 667-3783
