### ISSUE TITLE
Row color selected item

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Xamarin.Forms.DataGrid#55]
I have a problem on ios with deselecting an item. In the background the binding is null, but the surface still shows the selection. Any idea how to fix that?

Futhermore is there a possibilty to show the vertical/horizontal lines of the grid even with empty rows?

**Comment by SE250880** [comment]
Sorting columns on ios shows a similar bug. When I sort a column, it seems to me that the grid sets the selected item to null in the background but the surface still shows a darkgrey line.

**Comment by Essan-Augustin** [comment]
I have the similar bug on Android. Setting SelectedItem to null doesn't remove the selection background.
And setting SelectedItem by code is not reflected on the screen

**Comment by akgulebubekir** [comment]
same bug with #73, however its fixed
