### ISSUE TITLE
Header/Title is not showing from c# code

### ISSUE THREAD

**Issue by jszh23** [akgulebubekir/Xamarin.Forms.DataGrid#59]
I try to add Header on columns. if it's from XAML is working.
but when I try to add from c# code. the header is empty. here is my code. looks like the Title property is not working.
 public void SetDGColoumns()
        {
            int colNum=App.currentSheet.FieldInfoList.Count;
            RecordsDG.Columns.Clear();
            for (int k = 0; k < colNum; k++)
            {
                DataGridColumn dgc = new DataGridColumn();
                dgc.Title = App.currentSheet.FieldInfoList[k].FieldName;
                dgc.PropertyName = "DataFields[" + k + "].FieldValue";
                RecordsDG.Columns.Add(dgc);
            }
        }

**Comment by akgulebubekir** [comment]
since its not an observable collection, you should create the column list, then set.

i.e: 

				var columns = new ColumnCollection
				{
					new DataGridColumn
					{
						Title="col1",
						PropertyName = "p1",
					},
					new DataGridColumn
					{
						Title  ="col2",
						PropertyName ="p2",
					},
					new DataGridColumn
					{
						Title = "col3",
						PropertyName ="p3",
					}
				};

				datagrid.Columns = columns;

**Comment by jszh23** [comment]
Thanks for the solution. I tested, It's working!
