### ISSUE TITLE
Scroll in both directions?

### ISSUE THREAD

**Issue by JoeSchmeltzer** [akgulebubekir/Xamarin.Forms.DataGrid#60]
What would you recommend for scrolling in both directions on a grid that is wider than the screen?  I tried putting the data grid in a horizontal ScrollView and this technically works, but the device has a hard time figuring out whether the user wants to vertically scroll the data grid or horizontally scroll the ScrollView.  Example:
```
<ScrollView Orientation="Horizontal">
    <dg:DataGrid ItemsSource="{Binding Items}" SelectionEnabled="False" 
        ...
    </dg:DataGrid>
</ScrollView>
```
The result is that the horizontal ScrollView seems to be more sensitive so while scrolling vertically if you slide even slightly horizontal, the horizontal scroll takes over.  At that point the vertical scrolling stops.  This leaves a very annoying user experience.  Is there a better way to do this?  Ideally, I'd like to be able to just scroll in both directions at the same time.

**Comment by anovik** [comment]
I have problems with scrolling grid which is wide and have many items, too. The version which works best for the is the following:
```
<ScrollView Orientation="Both">
    <dg:DataGrid ItemsSource="{Binding Items}" SelectionEnabled="False" 
        ...
    </dg:DataGrid>
</ScrollView>
```
Horizontal scrolling is ok then, but vertical is very very slow (but working). Can it be solved?

**Comment by akgulebubekir** [comment]
DataGrid has its own vertical ScrollView, if you try to override it, that might cause some problem including performance and functionality. In fact its not even allowed to use ListView inside ScrollView. I don't think its a good idea to use ScrollView with DataGrid.

**Comment by BeBa-pL** [comment]
But how do I scroll horizontally now? Thanks
