### ISSUE TITLE
RowsBackground

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Xamarin.Forms.DataGrid#62]
With release 2.0. on ios the row background is drawn gray. Previously it was no color or white..... Using RowsBackgroundColorPalette shows exception

**Comment by akgulebubekir** [comment]
Instead of White, It updated with to transparent. You should use `RowsBackgroundColorPalette `instead as below.

```
  <dg:DataGrid.RowsBackgroundColorPalette>
    <dg:PaletteCollection>
      <Color>#FFFFFF</Color>
    </dg:PaletteCollection>
  </dg:DataGrid.RowsBackgroundColorPalette>
```

**Comment by SE250880** [comment]
It works.
Thank you!
