### ISSUE TITLE
Sorting Columns

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Xamarin.Forms.DataGrid#63]
Is there a way to specify the column sort e.g. sort a column by int value or date. At this moment it´s only string sorting???

**Comment by akgulebubekir** [comment]
implement `IComparable `interface for column property.

**Comment by SE250880** [comment]
Ok, is there anywhere an example?

**Comment by akgulebubekir** [comment]
http://bfy.tw/G6xu
