### ISSUE TITLE
Grid doesn't handle columns with no data properly

### ISSUE THREAD

**Issue by jwiese-ms-zz** [akgulebubekir/Xamarin.Forms.DataGrid#64]
When I provide a ItemsSource that has some missing data the grid doesn't properly setup each row.  For instance, if the first row is missing data (field=null) for the last two rows it creates a row with n-2 columns instead of properly creating a 'n' column row and placing the data in the columns correctly.  For instance create the following dataset:

New DataItem {Item1=0,Item2=12, Item3=4, Item4=null, item5=null}
New DataItem {Item1=98,Item2=16, Item3=12, Item4=null, item5=null}
New DataItem {Item1=121,Item2=45, Item3=121, Item4=4364, item5=468}
New DataItem {Item1=424,Item2=122, Item3=131, Item4=465, item5=3214}

Then set a grids ItemSource to the data.  The first two rows of data will only contain 3 columns spread across the grids 5 columns.

**Comment by akgulebubekir** [comment]
Could you please write your DataGrid definition, including columns?

**Comment by jwiese-ms-zz** [comment]
How about a repro :) (attached)  On UWP here is what you will see:

![image](https://user-images.githubusercontent.com/1899813/35392791-a4ca2096-01a8-11e8-81b1-b2736225fa91.png)

I believe you are using a listview item and probably just using the defined widths of the columns to create the items.  Since I have the last 2 columns defined as "auto" and there is nothing in the first three rows they take up "0" space and thus the incorrect output.  It's a hard problem to solve in XAML.  You basically have to re-walk the tree and set empty columns up to the width of the largest one.  Notice how if I make a slight change to the code to output a larger string into one columns of one row it throws it off even more:

![image](https://user-images.githubusercontent.com/1899813/35393008-5507e0b0-01a9-11e8-8510-de259d255beb.png)


[XamDG_Repro.zip](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/files/1664268/XamDG_Repro.zip)

**Comment by akgulebubekir** [comment]
You souldn't use `Auto `for column width. It should be star(*) or absolute.

Like:
`<xamdg:DataGridColumn ... Width="`~Auto~`*"/>`
