### ISSUE TITLE
How Get Selected Item using GestureRecognizer

### ISSUE THREAD

**Issue by rspulini** [akgulebubekir/Xamarin.Forms.DataGrid#65]
Greetings!

Congratulations on your component, it's really fantastic.

I need help. 
I added a column with Image. 
I'm using gesture recognition. I need to get selected item when the image is pressed. 
SelectedItem property is null.

How can I solve?  The code:

                        <dg:DataGridColumn SortingEnabled="False">
                            <dg:DataGridColumn.CellTemplate>
                                <DataTemplate>
                                    <Image Source="NovoDetalhePequeno.png" >
                                        <Image.GestureRecognizers>
                                            <TapGestureRecognizer BindingContext="{x:Reference Name=DetDocumento}" CommandParameter="{Binding Source={x:Reference grid}}"  Command="{Binding Path=BindingContext.SelecionadoComando}"  NumberOfTapsRequired="1" />
                                        </Image.GestureRecognizers>
                                    </Image>
                                </DataTemplate>
                            </dg:DataGridColumn.CellTemplate>
                        </dg:DataGridColumn>

**Comment by akgulebubekir** [comment]
`TapGestureRecognizer `triggers before than `SelectedItem`. You can pass the `SelectedItem `as `CommandParameter`.
```

<dg:DataGrid x:Name="myDataGrid">
    <dg:DataGridColumn SortingEnabled="False" PropertyName=".">
        <dg:DataGridColumn.CellTemplate>
            <DataTemplate>
                <Image Source="NovoDetalhePequeno.png" >
                    <Image.GestureRecognizers>
                        <TapGestureRecognizer CommandParameter="{Binding .}"  Command="{Binding ImageTapCommand,Source={x:Reference myDataGrid}}"/>
                    </Image.GestureRecognizers>
                </Image>
            </DataTemplate>
        </dg:DataGridColumn.CellTemplate>
    </dg:DataGridColumn>
</dg:DataGrid>
```

**Comment by rspulini** [comment]
Thanks for answering.

I tried to do so. But it is not working properly.

When I first press the image, the property SelectedItem is null. If I press another column, the row in question is selected. How to make the tap discover which line was pressed without selecting it?

It seems to me that the TapGestureRecognizertriggers happens first, when the property SelectedItem  has not yet been updated

**Comment by rspulini** [comment]
My friend, I'm sorry! Worked perfectly! Thank you very much. Congratulations on the excellent compotente.

**Comment by akgulebubekir** [comment]
You should use `CommandParemeter `instead `SelectedItem`

On Your VM : 

```
ImageTapCommand = new Command<YourObject>(YourMethod);

private void YourMethod(YourObject  tappedRow)
{
    // do your logic
}
```

p.s: Do not forget  `PropertyName="."`, `CommandParameter="{Binding .}"` and  `Command="{Binding ImageTapCommand,Source={x:Reference myDataGrid}}"`

**Comment by rspulini** [comment]
My friend, I'm sorry! Worked perfectly! Thank you very much. Congratulations on the excellent compotente.
