### ISSUE TITLE
How to deselect a row?

### ISSUE THREAD

**Issue by DiomedesDominguez** [akgulebubekir/Xamarin.Forms.DataGrid#73]
I tried to use the ```myGrid.SelectedItem = null;``` but it keeps showing the selected row.

**Comment by DanMburu** [comment]
I'm also having the same issue.Kindly advise on how to deselect a row.

**Comment by Sumit2668** [comment]
anybody find this solution ????????????

**Comment by Sumit2668** [comment]
getting error **# Specified cast is not valid.** with this code

>  grid.SelectedItem = false;

**Comment by Sumit2668** [comment]
I solved it...
               if (e.SelectedItem != null)
                {
                    grid.SelectedItem = null;
                }

**Comment by DiomedesDominguez** [comment]
Yes, but the Styles isn't applied correctly.
