### ISSUE TITLE
Column wider than screen problem

### ISSUE THREAD

**Issue by xFahim** [akgulebubekir/Xamarin.Forms.DataGrid#74]
Hi, 
I was using your amazing Datagrid and it was quite fascinating. But right now, in one of my applications, I have a pretty big Dataset and lots of columns which are also wider enough! 
So, I have seven columns and most of them contain decimal values which causes long width, as a result, it exceeds the screen width. And cutting out other columns. 

Is there any way I can add a Horizontal scrolling system over the datagrid columns or make them visible?

![ss1](https://user-images.githubusercontent.com/35301902/38043318-9df18bae-32d8-11e8-824c-a51583db871a.PNG)

**Comment by akgulebubekir** [comment]
Hi,
Xamarin.Forms has issues with nested scrolling and sometimes crashes the apps. In UWP its not even supported. Unfortunately it is not possible right now.

**Comment by xFahim** [comment]
Ok, thanks for mentioning!
