### ISSUE TITLE
ObservableCollection issues.

### ISSUE THREAD

**Issue by thomas-frantz** [akgulebubekir/Xamarin.Forms.DataGrid#75]
So I've got an issue with `ObservableCollection<T>` not triggering an update when set as the `ItemsSource` of the grid:

```cs
private ObservableCollection<MileageModel> _mileages;
public ObservableCollection<MileageModel> Mileages
{
	get => _mileages;
	set
	{
		_mileages = value;
		OnPropertyChanged(nameof(Mileages));
	}
}

// The view model constructor
public TheConstructor()
{
	Mileages = new ObservableCollection<MileageModel>();
}
```

And our grid:
```xml
<dg:DataGrid ItemsSource="{Binding Mileages}"  Style="{StaticResource dataGridStyle}" HeaderFontSize="14">
	<dg:DataGrid.Columns>
		<dg:DataGridColumn PropertyName="Period" Title="Period" HorizontalContentAlignment="Start"/>
		<dg:DataGridColumn PropertyName="TotalMileage" Title="Miles" HorizontalContentAlignment="Start" />
	</dg:DataGrid.Columns>

	<dg:DataGrid.RowsBackgroundColorPalette>
		<dg:PaletteCollection>
			<Color>#FAFAFA</Color>
			<Color>#F4F4F4</Color>
		</dg:PaletteCollection>
	</dg:DataGrid.RowsBackgroundColorPalette>
</dg:DataGrid>
```

Periodically a Timer ticks an update method, which pulls some data from our API and does this:
```cs
Mileages.Clear();
foreach (var mileage in data.Payload.Mileages)
	Mileages.Add(mileage);
```

This update tick is what triggers the collection to be populated, until this runs for the first time the collection is empty. When this update runs for the first time, I can see that it updated the collection - I've hooked into the `OnCollectionChanged` and I can print out how many it gets, I can see it's actively adding things to it. However, the visible grid remains empty and only displays two headers. The only way I can get the contents of the grid to show up is clicking one of the headers (as if to sort it) then the grid picks up the the new collection data and finally displays it.

I'm not sure if I'm just missing something of if there's a bug.

Thanks

**Comment by fedemkr** [comment]
I could workaround this by toggling the visibility of the grid off and on after the collection changes.

I've cloned the repository and tryiing to figure it out why the inner list view does not get updated

**Comment by njale** [comment]
Thanks for the work-around. Been struggling with this too. Works fine on UWP, but not on Android

**Comment by Kingdom-Of-Heaven** [comment]
I also face issue when my observablecollection list changed there is a problem with datagrid refresh. What is the best way to"help" grid to be refreshed correctly? I use MVVM pattern

**Comment by tkouba** [comment]
I have updated my application from Xamarin Forms 4.4 to 5.0 and I have this issue on Android.

**Comment by akgulebubekir** [comment]
This issue has already been resolved before and cannot be reproduced on the latest version. If you have any platform specific problem you can set propert instead of adding items into the `ObservableCollection`.


~Mileages.Clear();~
~foreach (var mileage in data.Payload.Mileages)~
~{~
~Mileages.Add(mileage);~
~}~

```
var items = new List<Mileage>(data.payload.Mileages);
Mileages = items;
```
