### ISSUE TITLE
UWP: Binding in CellTemplate doesn't work?

### ISSUE THREAD

**Issue by ionsharp** [akgulebubekir/Xamarin.Forms.DataGrid#79]
Take, for instance, the following:

    ...
    <dg:DataGridColumn 
        PropertyName="MyProperty"
        Title="My property">
        <dg:DataGridColumn.CellTemplate>
            <DataTemplate>
                <ContentView
                    BackgroundColor="Red"
                    HeightRequest="24"
                    WidthRequest="100">
                    <Label
                        TextColor="White"
                        Text="{Binding Path=MyProperty, Mode=OneWay}"/>
                </ContentView>
            </DataTemplate>
        </dg:DataGridColumn.CellTemplate>
    </dg:DataGridColumn>
    ...

`MyProperty` is never produced; just a red box. I tried changing `Path=MyProperty` to `Path=.` as well as omitting it altogether, but I still can't get the value to show. If I don't define a template for the column, `MyProperty` does show, but never otherwise.

I have only tested this with UWP.

**Comment by ionsharp** [comment]
After some more playing around, I found that `{Binding Path=.}` does produce the value, but `{Binding Path=MyProperty}` does not. Omitting a path will throw an exception. Was this intentional or a mistake? The documentation suggests you can access any of the properties from any given cell template, but as you can see, only the property specified by `PropertyName` is accessible.

**Comment by akgulebubekir** [comment]
Your cell automatically binds `PropertyName`, so you should use `{Binding .}`
