### ISSUE TITLE
Error when column header tapped

### ISSUE THREAD

**Issue by GlitchEclipse** [akgulebubekir/Xamarin.Forms.DataGrid#81]
I am in a UWP project and when launching threw the local machine simulator I am receiving an unhandled exception event when any of the column headers of the datagrid is tapped or clicked. If there a default to assign the column headers to so that the user clicking or tapping on the header does not throw this exception? 

![image](https://user-images.githubusercontent.com/20146526/39200414-b1238c34-47b1-11e8-872a-1ecdfcd42c09.png)

**Comment by akgulebubekir** [comment]
I need more information about this issue(like Xaml etc). Probably you're overriding `CellTemplate `with an invalid Xaml
