### ISSUE TITLE
Column Show and Hide

### ISSUE THREAD

**Issue by bharatkolla11** [akgulebubekir/Xamarin.Forms.DataGrid#85]
Hello,

I want to hide specific columns at the start of my app and on user settings i want them to show them or again hide them.

is there any component to do it ??

**Comment by akgulebubekir** [comment]
Bind columns to a list or update columns by setting

**Comment by BerndtHamboeck** [comment]
This did not work form me using Xamarin Forms for WPF. The header is not beeingrecreated. 
I used your source and made InitHeaderView public and called it after defining the columns in code.

                dataGrid.Columns.Clear();

                for (int i = 0; i < columnsDesc.Count; i++)
                {
                    dataGrid.Columns.Add(new Xamarin.Forms.DataGrid.DataGridColumn() { Title = columnsDesc[i], PropertyName = "Items["+i+"]" });

                }
                dataGrid.InitHeaderView();
