### ISSUE TITLE
Object Reference

### ISSUE THREAD

**Issue by bharatkolla11** [akgulebubekir/Xamarin.Forms.DataGrid#86]
<img width="1278" alt="screen shot 2018-05-27 at 10 15 03 am" src="https://user-images.githubusercontent.com/36744011/40587931-bfb801cc-619b-11e8-8ea0-aea04e3eb4c7.png">
Hello,

After Loading my application, it is showing me the error in the pic. May i know how to address it . What mistake i am doing.

**Comment by bharatkolla11** [comment]
<img width="1271" alt="screen shot 2018-05-27 at 11 13 19 am" src="https://user-images.githubusercontent.com/36744011/40588162-0d777bb0-619f-11e8-842d-c32777140293.png">

This is my Xaml Code.

**Comment by akgulebubekir** [comment]
I'm not sure the reason, but you might forget to call `Xamarin.Forms.DataGrid.DataGridComponent.Init() `before using.

**Comment by bharatkolla11** [comment]
I did use it in ios file. I used sortedcolumnindex = null. This is issue. Once i removed it , everything is working good

**Comment by akgulebubekir** [comment]
this issue should be fixed with 2.5.2-pre2
