### ISSUE TITLE
Same Problem as Object Reference #86

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Xamarin.Forms.DataGrid#89]
I use version 3.0.1-pre1 (current) with  .NETStandard 2.0 and Xamarin.Forms (>= 3.0.0.446417).
I got the same bug as described in #86.
I call 	Xamarin.Forms.DataGrid.DataGridComponent.Init(); in App.xaml.cs. Before updating from version 2.0.0 to version 3.0.1 everything works fine. Can you tell me how to fix it?

**Comment by akgulebubekir** [comment]
Should be fixed with [3.1.0](https://www.nuget.org/packages/Xamarin.Forms.DataGrid/3.1.0)
