### ISSUE TITLE
DataGrid Columns added programmatically don't show up

### ISSUE THREAD

**Issue by enantiomer2000** [akgulebubekir/Xamarin.Forms.DataGrid#90]
I have a DataGrid defined in XAML but I wan't to add the columns programmatically in the Page. When I add the columns with XAML, the headers show up just fine:
`<dg:DataGrid.Columns>
                <dg:DataGridColumn Title="Text1" PropertyName="Text1" />
                <dg:DataGridColumn Title="Text2" PropertyName="Tex2" />
                <dg:DataGridColumn Title="Text3" PropertyName="Text3" />
            </dg:DataGrid.Columns>`

but when I take out the XAML Columns and try to do it programmatically, only a dark grey background shows up:
`dgAssets.Columns.Add(new DataGridColumn() { Title = "Text1", PropertyName = "Text1" });
            dgAssets.Columns.Add(new DataGridColumn() { Title = "Text2", PropertyName = "Text2" });
            dgAssets.Columns.Add(new DataGridColumn() { Title = "Text3", PropertyName = "Text3" });`

This should be simple. Can it be that you cannot create a DataGrid with XAML and then create its Columns programmatically?

![columns_xaml_markup](https://user-images.githubusercontent.com/392371/41325529-ad244968-6e6f-11e8-80e3-e8f68f51f8d3.png)
![columns_programmatically](https://user-images.githubusercontent.com/392371/41325530-ad3da8ae-6e6f-11e8-8784-deccd40f6ef3.png)

**Comment by akgulebubekir** [comment]
In initial implementation we haven't made is Observable (shame on us :( )

You should create a new `ColumnCollection `and set Columns property with it.

```
	ColumnCollection cols=new ColumnCollection() ;

	cols.Add(new DataGridColumn() { Title = "Text1", PropertyName = "Text1" });
	cols.Add(new DataGridColumn() { Title = "Text2", PropertyName = "Text2" });
	cols.Add(new DataGridColumn() { Title = "Text3", PropertyName = "Text3" });

	DataGrid.Columns = cols;
```
