### ISSUE TITLE
DataGrid check list problem

### ISSUE THREAD

**Issue by RDMM1** [akgulebubekir/Xamarin.Forms.DataGrid#91]
Hello,
1. In my datagrid I have column with switches, and method switchToggled doesn't cointains infomartion about which switch has been toggled. I need to know, how to identify, which row was checked, is any solution of this?
2. I could do the same functionality with multiple selection, but couldn't find it in datagrid. 
Is any similar functionality like multiple row selection too?

Yours faithfully

**Comment by akgulebubekir** [comment]
Lets assume your `ItemsSource `is` List<TaskItem>` :
```
public class TaskItem
{
	public bool IsCompleted { get;set;}
	...
}
```

You need an implementation such

```
<dg:DataGridColumn Title="Active" PropertyName="IsCompleted" Width="100" SortingEnabled="False">
	<dg:DataGridColumn.CellTemplate>
		<DataTemplate>
			<Switch IsToggled="{Binding .}"/>
		</DataTemplate>
	</dg:DataGridColumn.CellTemplate>
</dg:DataGridColumn>

```

**Comment by RDMM1** [comment]
Thanks, but I still don't know which switch has been toggled. I don't know how bind switch with specifed row. Can you show some property or method from which I would be able to read toggled row?
