### ISSUE TITLE
How can I stretch to screen the Xamarin.Forms.DataGrid?

### ISSUE THREAD

**Issue by RanielQuirante** [akgulebubekir/Xamarin.Forms.DataGrid#92]
By default the Datagrid is not stretch fully in a content page, it is centered and then it has a little spacing over left and right, and this is really visible on a large screen when I tested it on UWP.

So, How can I stretch to screen the Xamarin.Forms.DataGrid?

![capture](https://user-images.githubusercontent.com/37047861/41500479-96c1f30c-71c4-11e8-8646-e71611dd858e.JPG)

**Comment by akgulebubekir** [comment]
You need to set `HorizontalOptions="FillAndExpand"` or place into a `Grid`

**Comment by RanielQuirante** [comment]
Apparently this didn't work for me :(
