### ISSUE TITLE
How come that "CellTemplate" is not an attachable property?

### ISSUE THREAD

**Issue by RanielQuirante** [akgulebubekir/Xamarin.Forms.DataGrid#93]
In the datagridsample, CellTemplate is an attachable property...

![original](https://user-images.githubusercontent.com/37047861/41500857-5ab21c0e-71cc-11e8-8146-bd6871f5ce9b.png)

But here on my application where I applied your datagrid, the property "CellTemplate" is not found... what did I do wrong here? please help...

![fake](https://user-images.githubusercontent.com/37047861/41500873-a143ea62-71cc-11e8-87a6-e46fc773069a.png)

**Comment by akgulebubekir** [comment]
`CellTemplate `is a property of `DataGridColumn`. If you want to set one you must create a `DataGridColumn `first.

```
<dg:DataGrid.Columns>
	<dg:DataGridColumn Title="Logo" PropertyName="Logo" Width="100" SortingEnabled="False">
		<dg:DataGridColumn.CellTemplate>
			<DataTemplate>
				<Image Source="{Binding}" HorizontalOptions="Center" VerticalOptions="Center" Aspect="AspectFit" HeightRequest="60" />
			</DataTemplate>
		</dg:DataGridColumn.CellTemplate>
	</dg:DataGridColumn>
	...
</dg:DataGrid.Columns>
```
