### ISSUE TITLE
Some of the CellBorder is missing in UWP

### ISSUE THREAD

**Issue by RanielQuirante** [akgulebubekir/Xamarin.Forms.DataGrid#95]
The three columns in the DataGridSample is okay, but the next two columns has its CellBorder greyed out or not colored, is this a bug? As you can see with Loss & Team

![capture](https://user-images.githubusercontent.com/37047861/41642321-8a3e5bd8-749a-11e8-9ebb-478897b487f4.JPG)

**Comment by akgulebubekir** [comment]
I'll investigate issue, but probably it caused from anti-aliasing. You might have a workaround by increasing the `BorderThickness`
