### ISSUE TITLE
Which switch has been toggeled?

### ISSUE THREAD

**Issue by stanustanley** [akgulebubekir/Xamarin.Forms.DataGrid#99]
I've got a problem with DataGrid, I have code like this:

```
<dg:DataGridColumn Title="Active" PropertyName="IsCompleted" Width="100" SortingEnabled="False">
	<dg:DataGridColumn.CellTemplate>
		<DataTemplate>
			<Switch IsToggled="{Binding .}"/>
		</DataTemplate>
	</dg:DataGridColumn.CellTemplate>
</dg:DataGridColumn>
```

```
public class TaskItem
{
	public bool IsCompleted { get;set;}
}

```
but now I need to know to which object of TaskItem I toggeled Switch, any suggestions?

**Comment by akgulebubekir** [comment]
There are 2 ways to do it:

1. If you are using MVVM:
    Override the setter of IsCompleted property and raise an event when toggled.

2. If you're not using MVVM:
    On xaml add Toggled event to the cell and write the method for xaml.cs Regarding the binding context you'll get the item.
